storage:
  # Supported database types: 'MySQL' and 'SQLite'.
  # Use 'MySQL' or 'SQLite' for server-based databases, or 'SQLite' for a lightweight file-based database.
  type: SQLite

  # The address of the database server.
  address: localhost

  # The name of the database to connect to or create.
  database: test

  # The username for the database connection.
  username: root

  # The password for the database connection.
  password: ''

  # SSL options (turned off by default)
  properties: '?useSSL=false&requireSSL=false&verifyServerCertificate=false'

  # Connection pool settings (for MySQL only).
  pool-settings:
    maximum-pool-size: 10
    maximum-idle: 10
    maximum-lifetime: 1800000
    keeplive-time: 0
    connection-timeout: 5000

  # Statement cache properties (optional)
  # These settings are used to optimize statement preparation and caching.
  # These should be specified for MySQL to improve performance.
  statement-cache-settings:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048

  # A prefix used for table names in the database.
  prefix: 'lr_'

#Allow shift right-click block or air to switch (page 1 row 1 slot) armor slot with the current.
shift:
  enabled: true
  #The lowest possible is 1. any lower is by default set to 1.
  cooldown: 10

# Configuration for the Locker command functionality in-game.
Command:
  # The primary name for the locker command used in-game.
  # Example: Setting this to 'locker' means players will use /locker in-game.
  name: 'lockers'  # This defines the command players will type.

  # A brief description of the /locker command for help menus or command listings.
  description: 'Explore the server in style!'  # Describe the command's purpose.

  # Instructions on how to properly use the command.
  # Provides users with an example usage format.
  usage: '/locker <sub command | optional>'  # Shows how to execute the command.

  #Permission to use the '/locker' command to open.
  permission: "lockers.use"

  # A list of aliases for the /locker command.
  # Players can use these shortcuts to invoke the command.
  # To disable aliases, simply set this to 'aliases: []'.
  aliases:
    - 'loc'
    - 'wardrobe'   # Allow players to use /wardrobe as a shortcut for /locker.
    - 'wr'    # Allow players to use /wr as a shortcut for /locker.

  #Aliases is not available in sub commands.
  subcommands:
    #Open another player's locker. (This should be limited to staff)
    open_locker:
      #This will look like '/locker open <player>'
      #If you change label it will be '/locker <change> <player>'
      label: "open"
      permission: "lockers.admin"
      usage: "&cUsage: &e/locker open <player>"

    reload_config:
      label: "reload"
      permission: "lockers.admin"
      usage: "&cUsage: &e/locker reload"


Gui:
  settings:
    max_pages: 5
  # Basic filler for empty slots in the GUI.
  # This is purely decorative to fill unused spaces.
  filler:
    material: GRAY_STAINED_GLASS_PANE
    display: " "
    lore: []

  # Main button players click to equip armor in a slot.
  # Shows when a slot is usable and provides access to armor management.
  equip:
    material: GREEN_STAINED_GLASS_PANE
    display: "&aEquip Armor"
    lore:
      - "&7Equip the armor placed in the slots above."
      - "&7If a slot is empty, it will remove"
      - "&7your currently equipped armor for that slot."

  # Slot shown when player lacks permission to unequip armor.
  # Gives visual feedback that removal isn’t allowed.
  unequip:
    material: RED_STAINED_GLASS_PANE
    display: "&cNo Permission"
    lore:
      - "&7You don't have permission to use this row."

  # Slot shown when armor is available to be equipped.
  # Provides visual indication that armor can be equipped in the slot.
  unused:
    material: WHITE_STAINED_GLASS_PANE
    display: "&7Slot Unavailable"
    lore:
      - "&7This slot is currently unused or unavailable."

  # Button to move to the next page in the GUI for more armor slots.
  next:
    material: PLAYER_HEAD
    display: "&aNext Page"
    lore:
      - "&7View additional armor slots on the next page."
    base64: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2M2MDJkYmE5Zjk3MDFhZTAwMzllNzQ4MWNlYmY2MWM1OGZlOGQzOWQyOWM5MjdiNDg4YmVlNDIyZDlhNjJkNCJ9fX0="

  # Button to go back to the previous page.
  back:
    material: PLAYER_HEAD
    display: "&aPrevious Page"
    lore:
      - "&7Go back to the previous page for other armor slots."
    base64: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjEzNGJhMjQxZjg3M2Q1ZWY0YzUyNmViMjkxYjVjMTZkNTA3ZDVhMGM2ZjFhMmU2NTAzZWM1OWIzNjNhMzY3NSJ9fX0="

  # Button to close the locker menu.
  # Lets players close the GUI with a single click.
  close:
    material: OAK_DOOR
    display: "&cClose Menu"
    lore:
      - "&7Click to close the locker menu."

misc_messages:
  error_command_permission: "&cYou don't have permission to use this command."
  error_player_exists: "&cNo record found for player &e%player%."
  error_row_permission: "&cYou don't have permission to access this row."
  gui_back_error: "&cYou're already on the first page."
  gui_last_error: "&cYou're on the last page."
  success_command_reload: "&aReloaded configurations."